USE TrabalhoInfantil;

SELECT B.UF,B.NOUF AS Estado,B.Regiao,SUM(CAST(PESO AS DECIMAL)) AS QUANTIDADE
FROM tbpnadc as A
INNER JOIN (SELECT DISTINCT UF,CDUF,NOUF,Regiao FROM tbmunicipios) AS B ON A.CDUF = B.CDUF
WHERE IDADE < "018" 
AND ANO = "2019"
AND (TRABDINHEIRO = "1" OR TRABNATURA = "1" OR BICO = "1" OR TRABSEMRECEBER = "1" OR TrabDinheiro5a13 = "1" OR TRABNATURA5a13 = "1" OR Bico5a13 = "1" OR TrabSemReceber5a13 = "1")
GROUP BY B.Regiao,B.UF,B.NOUF
ORDER BY QUANTIDADE DESC;